### ISSUE TITLE
Muy buen trabajo!

### ISSUE THREAD

**Issue by danmt** [leandrogavidia/heavy-duty-builders-solana-bootcamp#2]
Que bien que hayas creado un branch, asi puedes ver el progreso luego! 

Tu proyecto está casi listo. Al correrlo con `nx serve` da un error de process, el ejemplo de polyfills tiene un error. Para arreglarlo, reemplaza el contenido de [los polyfills](https://github.com/leandrogavidia/heavy-duty-builders-solana-bootcamp/blob/challenge-1/src/polyfills.ts) con este codigo:

```typescript
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Buffer } from "buffer";

(window as any).global = window;
(window as any).global.Buffer = Buffer;
(window as any).process = { env: { }};  
```

**Comment by leandrogavidia** [comment]
@danmt Cambio realizado, muchas gracias :D
